services:

  nginx_01:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www
      - ./logs/nginx:/var/log/nginx
    networks:
      - app_network_01

networks:
  app_network_01:
    driver: bridge